### ISSUE TITLE
Ninja build failed

### ISSUE THREAD

**Issue by mustakimur** [HexHive/CFIXX#3]
Hi
I follow the build script provided in the repo and found it failed in following:
```
~/llvm/projects/compiler-rt/lib/esan/esan_sideline_linux.cpp:73:22: error: aggregate ‘sigaltstack SigAltStack’ has incomplete type and cannot be defined
   struct sigaltstack SigAltStack;
```
I believe this is not an error from CFIXX code, but the release version of LLVM-CLang it uses. Can you please integrate it with a more stable release?

**Comment by nburow2** [comment]
I just cloned the repo and built using cmake 3.11.2 and ninja 1.8.2 .  I used clang 7.0 (the head) to build as that's what I have installed, I can check with clang-6.0 (latest release) if necessary, but doubt that is the problem.  The main compiler built fine, I'm having an issue with libcxx, specifically cmake for libcxxabi isn't finding the libunwind dependency for some reason.

**Comment by nburow2** [comment]
Okay - turns out that they shouldn't be looking for the unwind tests when building libcxxabi standalone.  I updated their CMake file as per later versions of LLVM to fix this.  If you pull and rerun the ./install-cfixx-files.sh command and do a make it should all build.
