### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by sqall01** [HexHive/CFIXX#5]
Hi,
the project also has a dependency to the binutils-dev package (package name from ubuntu). Otherwise you get an error message like this:

```bash
sqall@de0b:/media/sqall/27B98FA87615EE0A/cfixx/CFIXX/llvm/tools/gold/gold-plugin.cpp:52:10: fatal error: 'plugin-api.h' file not found
#include <plugin-api.h>
         ^
1 error generated.
[2085/2662] Linking CXX shared library lib/libLTO.so
ninja: build stopped: subcommand failed.
```

Also, I had to insert in the `release_cmake.sh` file the following option: `-DCMAKE_ASM_COMPILER=clang` to the cmake command. Otherwise it would not configure the project.

Cheers,
Andre

**Comment by nburow2** [comment]
Yes - I should make a list of assumed dependencies and add them to the readme.  binutils-dev supports building the gold linker plugin, though that's not strictly necessary for this project as we don't need LTO, I just have it configured by default on my systems.  

I've never had to use the asm_compiler flag, that's odd.  What version of clang were you using to compile the project?

**Comment by sqall01** [comment]
I used clang-3.8

**Comment by nburow2** [comment]
I updated the README to include more details on the system environment that I used.
